### ISSUE TITLE
Adaptive for in about page

### ISSUE THREAD

**Issue by Talerchik-Aleksey** [FaetterP/o6i7ry#17]
![o6i7ry onrender com_](https://github.com/FaetterP/o6i7ry/assets/74420840/24aee8d1-7693-4e96-acef-33ed0b32fa34)

**Comment by souliriss** [comment]
35d5352471af30054536671b74572ca2220eae9

**Comment by souliriss** [comment]
235d5352471af30054536671b74572ca2220eae9
