### ISSUE TITLE
Исправить предупреждение с импортом шрифтов

### ISSUE THREAD

**Issue by FaetterP** [FaetterP/o6i7ry#7]
Ссылка на документацию: https://nextjs.org/docs/messages/google-font-display  
Нужно исправить это предупреждение:  
![image](https://github.com/FaetterP/o6i7ry/assets/56697273/f179cb2d-a042-49ca-8808-5033881e7228)

**Comment by souliriss** [comment]
Исправлено
![image](https://github.com/FaetterP/o6i7ry/assets/49311771/42de70e2-1ec0-4f69-8e23-6dc7128fb932)
